apiVersion: v1
kind: Service
metadata:
  name: letssee444
spec:
  selector:
    app: letssee444
  ports:
  - name: web
    nodePort: 30084
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
